#+STARTUP: showall indent
#+STARTUP: hidestars
#+OPTIONS: toc:nil num:nil
#+BEGIN_HTML
---
title: About
layout: default
---
#+END_HTML
   
* About This Website

Moving from Paris to San Francisco a few month ago was a huge change in my life on a lot 
of levels. One of them being the way I approched my carrer and the whole hiring process. 
According to my experience, the main difference is that in France the hiring person will 
first look at where you come from as when in the US they will look at your skills first, 
which in my book is a better way. The main inconvinience (which is also an advantage) 
of this process is that you have to be sharp all the times on a very large span 
of technical skills. So to avoid surprises and be "interview ready" I started studying 
old and new stuffs. So this website is here to keep track of everything, and also provide
support for my memory and limit the studying time before and interview.
      
* Fabien Cesari

Musician, developer, engineer in signal processing and electronics 
from [[http://www.ensea.fr][l'Ecole Nationale Superieur de l'Electronique et de ses Applications (ENSEA)]] 
in Paris, France. I have been working for companies such as  [[http://www.voxler.fr/][Voxler Games]] and [[http://www.arkamys.com/home.php][Arkamys]]. 
For the past year I worked at [[http://www.ircam.fr/"][L'Institut de Recherche et Coordination Acoustique / Musique (IRCAM)]] 
in Paris, France.	   

My music is largely based on improvisation, incorporating multiple facets of electroacoustic
music such as digital and analogue electronic experimentation, collage, tape music, field 
recordings and the use of recorded music as a raw material. For this purpose, I design 
hardware and software tools. I also create automatic compositions based on algorithms that 
simulate guided random walks. While my work is undeniably artistically-motivated, my process 
is nevertheless influenced by, and in some instances, dependent on my 
technical and scientific foundations.

I am currently looking for employment opportunities in San Francisco and in the Bay Area. 
I am eager to discover new technologies and augment my skill set, and I am very open to new 
fields of applications. I am devoted to interdisciplinarity and I look forward to participating 
in like-minded dialogues, characteristic of the technology community in the region.  

I am happy to provide more information about myself, 
so please [[mailto:fabien.cesari@magnizdat.org][contact me]] download my full [[file:docs/FabienCesari_CV.pdf][Curriculum here]].

